# ページのtitleタグの内容
title = "Status Page"
# ナビゲーションバー上のタイトル markdown可
nav_title = "[Status Page](https://github.com/kazeburo/statusboard/) DEMO"
# ナビゲーションバー上のボタンの名前
nav_button_name = "HOME"
# ナビゲーションバー上のボタンのリンク先
nav_button_link = "/"

# トップのメッセージ markdown可
header_message = ""
# フッターメッセージ markdown可
footer_message = """
ページ上のメッセージ
- markdownが書けます
- [GitHub](https://github.com/)
"""

# フッターテキスト markdown可
powered_by = "Powered by statusboard"

# ヘルスチェックの並列稼働数
num_of_worker = 4
# ヘルスチェックのリトライ回数
max_check_attempts = 3
# ヘルスチェックに失敗した際のスリープ時間
retry_interval = "3s"
# ヘルスチェックの間隔
worker_interval = "1m"
# ヘルスチェックコマンドの最大待機時間
worker_timeoout = "30s"
# 最新のステータスとして扱う時間範囲
latest_time_range = "1h"

[[category]]
name = "グローバル"
comment = "グローバルサービス"

[[category.service]]
name = "だいじなサービス"
command = ["sh", "-c", "echo stdout; echo 1>&2 stderr && exit 0"]

[[category.service]]
name = "いつものサービス"
command = ["sh", "-c", "echo stdout; echo 1>&2 stderr && exit 3"]

[[category]]
name = "プライベート"
comment = "プライベートサービス"

[[category.service]]
name = "DNSサービス"
command = ["sh", "-c", "echo stdout; echo 1>&2 stderr && exit 0"]

[[category.service]]
name = "HTTPサービス"
command = ["sh", "-c", "echo stdout; echo 1>&2 stderr && exit 3"]
